### ISSUE TITLE
right align text in footer

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#128]
![image](https://user-images.githubusercontent.com/68149849/131529864-fcb3ed48-09c9-4a00-8b2f-377179e6ba58.png)

'Quick links' should be right aligned

**Comment by AKSHATNEMA** [comment]
Hi @shikha-16, I want to take up this issue. Kindly assign it to me and I will take this issue under hacktoberfest.
Rest solutions for this issue will be conveyed to you soon on discord.
