### ISSUE TITLE
Make all fonts, images and alignments in the website consistent.

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#135]
Make all font themes and sizes as well as image sizes in the website consistent, across all pages.

**Comment by AKSHATNEMA** [comment]
@shikha-16, will you please elaborate in what way and where you want to make the images, text, fonts consistent over the website?

**Comment by shikha-16** [comment]
> @shikha-16, will you please elaborate in what way and where you want to make the images, text, fonts consistent over the website?

Hi, I can elaborate more over a call maybe. Please join the discord community so i can let you know exactly what I want. Thanks!
