### ISSUE TITLE
Need a logo for the website.

### ISSUE THREAD

**Issue by umang-sinha** [shikha-16/Women-in-Technology#14]
A small logo for the website is required. The logo will be displayed in the top navigation bar. Please check out the design in the following link to get an idea about the theme of the website:

https://www.figma.com/file/zsYoyOajOsYONxlPdNLiSf/Women-in-Technology?node-id=2%3A1

**Comment by RafaelDavisH** [comment]
Are there any logo prototypes for reference? I'm interested to help with the logo design.

**Comment by umang-sinha** [comment]
Hey Rafael! I hope you might have gone through the design prototype in the figma link attached in my previous comment to get a feel of the theme that we are looking to build upon. We are looking for a minimalistic logo that pertains to the theme. For reference you might have a look at the logo of these websites:
https://womenintechnology.in/ 
https://www.womenintechnology.org/

**Comment by bharati-21** [comment]
Hello @umang-sinha, if this issue has not been assigned would like to work on this. 

Thank you!

**Comment by shikha-16** [comment]
@RafaelDavisH please inform if you have gone through the resources and are still interested. Since you commented first, you will be given preference, if not then @bharati-21 can take this issue up.

@bharati-21 @RafaelDavisH also inform if any of you would you be willing to work with @umang-sinha for enhancements in website design, i.e. [this issue](https://github.com/shikha-16/Women-in-Technology/issues/15)

**Comment by bharati-21** [comment]
Thank you @shikha-16. Yes, I would like to work on [this issue](https://github.com/shikha-16/Women-in-Technology/issues/15).

**Comment by shikha-16** [comment]
> Thank you @shikha-16. Yes, I would like to work on [this issue](https://github.com/shikha-16/Women-in-Technology/issues/15).

hi @bharati-21 great, comment over there and i'll assign it to you

**Comment by RafaelDavisH** [comment]
Yes, I'm interested in working on this issue and possibly taking a look in the website as well.

**Comment by RafaelDavisH** [comment]
If assigned to me I'll start asap.

**Comment by shikha-16** [comment]
Sure @RafaelDavisH 

Do provide a rough idea when you'll be able to complete?

**Comment by RafaelDavisH** [comment]
I estimate about Saturday or Sunday to some rough drafts. Would this work?

**Comment by shikha-16** [comment]
@RafaelDavisH , yes that's great! please provide your timezone for exact details.

Also, website design is of higher priority rn. If you want to be assigned that too (it'll help), please do comment over there as well. 
And do join the discord server (given in the repo) for further discussions about issues. 

Thank you!

**Comment by johnnyduo** [comment]
Great

**Comment by RafaelDavisH** [comment]
PT - LA California. Okay I'll comment there now.

**Comment by pratheek-shett** [comment]
Hii where to submit my created logo is it applicable for hactoberfest 2020

**Comment by shikha-16** [comment]
> Hii where to submit my created logo is it applicable for hactoberfest 2020

@pratheek-shett I'm sorry, this issue has already been taken up by Rafael. Check out the issues that haven't been assigned to anyone yet, if you still wish to contribute. Thank you.

**Comment by pratheek-shett** [comment]
I can I pull or push the logo to github

**Comment by wannabehacker007** [comment]
I can be of help, could you please assign me this one? I'm also going to comment on the few other ones where I can provide my assistance.

**Comment by RafaelDavisH** [comment]
@shikha-16 I have sent you an invited for the Logo draft. I pickes some of the colors that were used of the Carousel.

**Comment by pratheek-shett** [comment]
Ok thank you. Is the invit in github

**Comment by pratheek-shett** [comment]
Can you please tell me how can I pull request a logo

**Comment by shikha-16** [comment]
@pratheek-shett please stop commenting on this issue. I have already said it has been assigned to someone else, and it does not concern you.
