### ISSUE TITLE
Merge the Beginners and Guidelines pages

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#140]
![Screenshot from 2021-09-03 00-20-14](https://user-images.githubusercontent.com/68149849/131900042-ac4c2e6b-c336-4981-b351-d713d73209d7.png)
Transfer this content to the 'Guidelines' page at the bottom of page.

**Comment by priyansh71** [comment]
Should the Beginner's page link from the Navbar be removed then? If yes, assign this issue to me, I'd like to work on it.

**Comment by shikha-16** [comment]
> Should the Beginner's page link from the Navbar be removed then? If yes, assign this issue to me, I'd like to work on it.

Yes, and its contents to be transferred to Guidelines.
I'm assigning you

**Comment by priyansh71** [comment]
I've made a [pull request](https://github.com/shikha-16/Women-in-Technology/pull/171) regarding the same. Please, have a look at it.

**Comment by priyansh71** [comment]
Can this issue be closed now?
