### ISSUE TITLE
Link text on repository to text on website

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#141]
I want to know if its possible to link the repo and website contents. If I make changes in the repo README, I want it to automatically update on the website.

**Comment by nayabatir1** [comment]
Hi @shikha-16 may I help

**Comment by shikha-16** [comment]
> Hi @shikha-16 may I help

yeah sure. please join the discord channel and we can connect there!

**Comment by nayabatir1** [comment]
@shikha-16 can share an invite

**Comment by shikha-16** [comment]
@nayabatir1 https://discord.com/invite/j9eM73g7hH

**Comment by sungod12** [comment]
Hi @shikha-16 ,can you clarify the issue a little more. Are you referring to readme.md on your repo. If yes, I cannot find where it is used in your website?

**Comment by shikha-16** [comment]
> Hi @shikha-16 ,can you clarify the issue a little more. Are you referring to readme.md on your repo. If yes, I cannot find where it is used in your website?

Hey, please message me on discord and we could find a time to talk about this in more detail!

**Comment by nayabatir1** [comment]
> > Hi @shikha-16 ,can you clarify the issue a little more. Are you referring to readme.md on your repo. If yes, I cannot find where it is used in your website?
> 
> Hey, please message me on discord and we could find a time to talk about this in more detail!
Please provide provide some more time.
I'm affected by flood 😔. Not possible to work for couple of days.

**Comment by shikha-16** [comment]
> > > Hi @shikha-16 ,can you clarify the issue a little more. Are you referring to readme.md on your repo. If yes, I cannot find where it is used in your website?
> > 
> > 
> > Hey, please message me on discord and we could find a time to talk about this in more detail!
> > Please provide provide some more time.
> > I'm affected by flood pensive. Not possible to work for couple of days.

Oh, okay sure @nayabatir1. Take care!

**Comment by shikha-16** [comment]
> > > > Hi @shikha-16 ,can you clarify the issue a little more. Are you referring to readme.md on your repo. If yes, I cannot find where it is used in your website?
> > > 
> > > 
> > > Hey, please message me on discord and we could find a time to talk about this in more detail!
> > > Please provide provide some more time.
> > > I'm affected by flood pensive. Not possible to work for couple of days.
> 
> Oh, okay sure @nayabatir1. Take care!

@sungod12 let this issue stay with @nayabatir1 for now. Thanks!
