### ISSUE TITLE
a tag Link color not changing according to dark mode 

### ISSUE THREAD

**Issue by shreyshreyansh** [shikha-16/Women-in-Technology#142]
![Screenshot-2021-09-08-095425](https://user-images.githubusercontent.com/53744971/132446816-8af2cd48-7528-43a7-a7aa-b92583cedde6.jpg)

**Comment by shikha-16** [comment]
@shreyshreyansh are you working on this?

**Comment by aexcode** [comment]
Hello! If the original assignee is no longer working on this, I would love to help out!

**Comment by sungod12** [comment]
Hi @shikha-16 @nehakalbande, if nobody is working on this issue. Can I work on it?

**Comment by shreyshreyansh** [comment]
> @shreyshreyansh are you working on this?

Sorry I am currently busy in my college placements.. So I won't be able to work on this issue

**Comment by sungod12** [comment]
I am working on this issue .So could anyone of you assign me this issue, if anyone is not working @nehakalbande @shikha-16 .
