### ISSUE TITLE
Proper spacing between the logo and title of website on navbar

### ISSUE THREAD

**Issue by AKSHATNEMA** [shikha-16/Women-in-Technology#146]
**Is your feature request related to a problem? Please describe.**
The logo and title in the navbar are getting too much close to each other and also they are sticking towards the left in the window.

**Describe the solution you'd like**
It can easily be solved by providing proper margins and padding to both icon and title in the navbar. It may happen that mobile view has to be resolved according to that, but it can be handled easily.

**Describe alternatives you've considered**

**Additional context**
![website](https://user-images.githubusercontent.com/76521428/134762669-13aa6026-c4b2-4ba0-b777-58d2defb43e7.png)

If you can, please give this issue hacktoberfest tag and assign it to me if you can.

**Comment by shikha-16** [comment]
Okay @AKSHATNEMA please go ahead!
