### ISSUE TITLE
Add Given Sites In the Events/Programs Page 

### ISSUE THREAD

**Issue by nehakalbande** [shikha-16/Women-in-Technology#147]
- Alexa Student Influencers
- WomenTechmakers Ambassador
- Google Developer Student Clubs
- Microsoft Student Learn Ambassadors Program
- MLH Fellowship
- Github Campus Expert

**Comment by Jayita10** [comment]
Hi, Please assign this issue to me so that I can work on this

**Comment by shikha-16** [comment]
@Jayita10 when you're on this, can you also work on #130 
Iwilladdign them both to you and you can make separate PRs for them as well.

**Comment by Jayita10** [comment]
> @Jayita10 when you're on this, can you also work on #130
> I will assign them both to you and you can make separate PRs for them as welO


> @Jayita10 when you're on this, can you also work on #130
> I will assign them both to you and you can make separate PRs for them as well.

Okay sure :)

**Comment by shikha-16** [comment]
> > @Jayita10 when you're on this, can you also work on #130
> > I will assign them both to you and you can make separate PRs for them as welO
> 
> > @Jayita10 when you're on this, can you also work on #130
> > I will assign them both to you and you can make separate PRs for them as well.
> 
> Okay sure :)

Can you please comment on #130  so that I can assign it to you

**Comment by Jayita10** [comment]
I have update the readme. What else need to be updated?

**Comment by nehakalbande** [comment]
Hi @Jayita10 need this links in the Events/Programs page of website too

**Comment by Jayita10** [comment]
> Hi @Jayita10 need this links in the Events/Programs page of website too

Hi @nehakalbande, I am not able to find the location of Events/Programs page. Will you please help me 😕

**Comment by nehakalbande** [comment]
website/src/pages/events.js
