### ISSUE TITLE
Remove warnings for unused imports 

### ISSUE THREAD

**Issue by sungod12** [shikha-16/Women-in-Technology#149]
Description-
Whenever the website is served on localhost for testing, there are lot of warnings for unused imports . Appropriate screenshot has been shared with @nehakalbande on discord. 

Solution-
If you want to still use those imports at a later time without the need to remember where they were being used, all unused imports can be stored in txt file with appropriate path names above each import so that they could be referenced again in future.

**Comment by shikha-16** [comment]
Okay @sungod12 go ahead!

**Comment by sungod12** [comment]
Hi @nehakalbande ,unable to add pull request

**Comment by nehakalbande** [comment]
> Hi @shikha-16 ,unable to add pull request

What's the error?

**Comment by sungod12** [comment]
actually O referenced the issue here, but I cannot seem to add pull request from the repo I forked as when I try to open a new pull request, it shows like this 👇
![image](https://user-images.githubusercontent.com/55348832/135596124-11cdf342-a3f7-46bc-9e62-dcaee61ef7ea.png)

**Comment by nehakalbande** [comment]
> actually I referenced the issue here, but I cannot seem to add pull request from the repo I forked as when I try to open a new pull request, it shows like this 👇. Also I am new to this request. Any idea what I am doing wrong? ![image](https://user-images.githubusercontent.com/55348832/135596124-11cdf342-a3f7-46bc-9e62-dcaee61ef7ea.png)

We haven't accepted your previous PR yet, that's why this issue has occurred . We'll accept the PR by tonight

**Comment by sungod12** [comment]
Oh okay !. I thought about that in first place. Thanks for confirmation.
