### ISSUE TITLE
Enhancements for the website design needed

### ISSUE THREAD

**Issue by umang-sinha** [shikha-16/Women-in-Technology#15]
The design for the website is in the initial phase of development. Do suggest changes if you have better ideas to further enhance the theme or the color palette. Check out the design here:

https://www.figma.com/file/zsYoyOajOsYONxlPdNLiSf/Women-in-Technology?node-id=2%3A1 (feel free to ask for edit access to the figma project if you are willing to work on the design)

**Comment by bharati-21** [comment]
I would like to work on this @umang-sinha @shikha-16. 
Please do inform me if I have a deadline! Thank you.

**Comment by shikha-16** [comment]
> I would like to work on this @umang-sinha @shikha-16.
> Please do inform me if I have a deadline! Thank you.

Yes, website design is of the highest priority as of now. We would like it to be done by October 12, 9 PM IST.
Do join the discord server (given in the repo) for further discussion. You'll have to collaborate with @umang-sinha and possible other contributors in this task. 

Thank you for choosing to contribute, and welcome to the community!

**Comment by umang-sinha** [comment]
@bharati-21 please provide the email ID that is linked to your figma account so that I can provide you edit access for the design project. In case you don't have a figma account, I request you to make one.

**Comment by RafaelDavisH** [comment]
Is there room for one more ? Interested in helping in any way with the website enhancements

**Comment by bharati-21** [comment]
Thank you @umang-sinha 
My email ID: bharatisharada@gmail.com

**Comment by bharati-21** [comment]
Also, please do provide any additional information I should know before starting the enhancement. 
Thank you.

**Comment by umang-sinha** [comment]
@bharati-21 I have provided you edit access to the figma project. You may begin working on the design.

**Comment by umang-sinha** [comment]
@RafaelDavisH please provide the email ID linked with your figma account so I can provide you access to the figma project.

**Comment by RafaelDavisH** [comment]
Thinkprintgrafx@gmail.com

**Comment by umang-sinha** [comment]
@RafaelDavisH I have sent you an invite. Please accept it.

**Comment by shikha-16** [comment]
@bharati-21 please join the discord group. There is a meeting scheduled today at 3pm IST. The link is on discord. Please be there.

**Comment by bharati-21** [comment]
@shikha-16, yes. I will be there. Thank you!
