### ISSUE TITLE
Issue related to Image loading time

### ISSUE THREAD

**Issue by madhhuurrii** [shikha-16/Women-in-Technology#151]
Problem :
At times when loading the website it is observed that images are taking time to get load  in mobile view.

Solution : 
May be we can use imgbot for better optimization of images which can help in compressing the images whenever added to the repository. Instead of relying on other compressing tools, Imgbot can do it automatically.  Thus the image loading time can get reduced considerably!

**Comment by nehakalbande** [comment]
Hi @madhhuurrii Yes, the images take time to load.  Imgbot is a good idea.
One more solution is to change all images into svg, loading time will get reduce.

**Comment by madhhuurrii** [comment]
Yes @nehakalbande we can consider svgs too, but if contributors add in png format we might have to manually change the format I guess

**Comment by nehakalbande** [comment]
Correct, Will you work on it?

**Comment by madhhuurrii** [comment]
I guess I cannot add the img bot through PR , instead can add it directly in the repository. If possible I'll look into it and create a PR

**Comment by nehakalbande** [comment]
If you are able to add a PR over this issue. Please do let us know :)

**Comment by madhhuurrii** [comment]
I tried reading some documentation of ImgBot, it can be only added by someone who has access to this repository. So I can not make PR for this issue.

**Comment by nehakalbande** [comment]
Okay, no worries :)
