### ISSUE TITLE
Reduce Images width in Organizations , Scholarships Page

### ISSUE THREAD

**Issue by nehakalbande** [shikha-16/Women-in-Technology#152]

**Comment by ruchika-01p** [comment]
May i work on this?

**Comment by nehakalbande** [comment]
Sure @ruchika-01p Assigning to you :)

**Comment by AKSHATNEMA** [comment]
@nehakalbande, this issue has already been raise in issue #135, and I am already working on it. Kindly check it.

**Comment by nehakalbande** [comment]
Yup, Work on it @AKSHATNEMA Reduce Images width

**Comment by shikha-16** [comment]
@ruchika-01p please note the change above, sorry for the inconvenience. You are welcome to take up any other issue!
