### ISSUE TITLE
Fix the About Community Page in Dark Mode

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#165]
![image](https://user-images.githubusercontent.com/68149849/135719067-0c832f5b-0dd3-44d2-b903-e99696ff832f.png)

Update this page and all its cards to appear in dark mode properly.

**Comment by swapnil604** [comment]
I'd love to work on it. If you think I'm eligible kindly assign.

**Comment by nehakalbande** [comment]
Yes sure @swapnil604 Work on it

**Comment by Pulkit007** [comment]
Hey Is anyone still working on it.
If this issue is free can I work on this?

**Comment by shikha-16** [comment]
@swapnil604 @Pulkit007 is anyone working on this?

**Comment by swapnil604** [comment]
No, you can proceed. Apologies for not responding I have exams around the corner.
