### ISSUE TITLE
 Issues in carousel

### ISSUE THREAD

**Issue by sungod12** [shikha-16/Women-in-Technology#179]
Description-
-The first image in carousel appears left aligned and smaller than other images, which appears not good when that image comes after sliding through each image. 
-Also the button are technically not visible because of white background, even though the carousel is automatic.
-The images size appear kind of zoomed out due to which they look blurry.

Suggested Solution-
-I observed that due to id="loggs",the first image is left aligned, removing that fixes the first issue.
-The buttons color could be changed to other color which would look visible on the carousel, and distinguished easily.
-Good quality images could be used, which could take time to load, but that can only be know once they are rendered.

**Comment by priyansh71** [comment]
I can make a pull request fixing the first two points of the issue.
For solving the "Good quality images" issue, does the project require different better quality images, or a better version of the same images?

**Comment by sungod12** [comment]
> I can make a pull request fixing the first two points of the issue.
> For solving the "Good quality images" issue, does the project require different better quality images, or a better version of the same images?

better version of same images.

**Comment by sungod12** [comment]
> > I can make a pull request fixing the first two points of the issue.
> > For solving the "Good quality images" issue, does the project require different better quality images, or a better version of the same images?
> 
> better version of same images.

actually i was going to work on this issue .

**Comment by shikha-16** [comment]
This issue is already there #314
closing
