### ISSUE TITLE
Reducing size of social icons and add space between them

### ISSUE THREAD

**Issue by Hina-softwareEngineer** [shikha-16/Women-in-Technology#187]
**Is your feature request related to a problem? Please describe.**
The social Icons size of LinkedIn and github is too large and one has border-radius and one doesn't have which is a bad UX practice. Also, Both Icons have no space in-between.

**Describe the solution you'd like**
Social Icons width and height can be reduced and add padding to both Icons with a good border-radius.

**Additional context**
![z](https://user-images.githubusercontent.com/56507951/137071090-cc5655c1-ebf6-44cf-88f2-478ba27c9f2f.png)

**Comment by Hina-softwareEngineer** [comment]
Also Can I work on this issue ?

**Comment by shikha-16** [comment]
> **Is your feature request related to a problem? Please describe.** The social Icons size of LinkedIn and github is too large and one has border-radius and one doesn't have which is a bad UX practice. Also, Both Icons have no space in-between.
> 
> **Describe the solution you'd like** Social Icons width and height can be reduced and add padding to both Icons with a good border-radius.
> 
> **Additional context** ![z](https://user-images.githubusercontent.com/56507951/137071090-cc5655c1-ebf6-44cf-88f2-478ba27c9f2f.png)

Yes, this is a valid issue and since you opened it, I will assign it to you.

**Comment by shikha-16** [comment]
> Is anyone working on this? If not please assign this to me.

hi @Pulkit007 can you work on #166 instead?

**Comment by Pulkit007** [comment]
> > Is anyone working on this? If not please assign this to me.
> 
> hi @Pulkit007 can you work on #166 instead?

Okay
