### ISSUE TITLE
Looking for wireframe designers for the website

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#24]
If you're interested to work on the wire frame design for the website, please comment here.

**Comment by bekmuradov** [comment]
Hi, I am interested!

**Comment by tory-brown** [comment]
I'm available to work on the wireframe.

**Comment by shikha-16** [comment]
Hi @tory-brown I'm so sorry, this issue has been taken up by two other people already. Would you be interested in working on the actual designing of the website using the wireframes?

**Comment by tory-brown** [comment]
thats ok. yes I would love to

**Comment by shikha-16** [comment]
> thats ok. yes I would love to

Please go through Contributing.md, comment on the relevant issue and join the discord server for the same. Thank you!

**Comment by tory-brown** [comment]
ok

**Comment by shikha-16** [comment]
@tory-brown we need graphic designers for the website, please message if you are willing to take something up
