### ISSUE TITLE
Looking for graphic designers for website.

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#27]
The basic wireframes are complete, we need designers to work on the actual finishing design of the website. If you are experienced in this field, please do contribute! Refer to the wireframes [here](https://github.com/shikha-16/Women-in-Technology/tree/master/documents/wireframes).

- [ ] Homepage
- [ ] Community/About Us
- [ ] Organizations
- [ ] Scholarships
- [ ] Resources
- [x] Inspirations
- [ ] The World of CS
- [ ] Contribute

Separately, I need designs for each carousel.
- [x] Homepage
- [x] World of CS
- [x] Organizations
- [x] Inspirations
- [x] Scholarships

Whoever wants to contribute HAS to comment here AND join the [Discord](https://discord.com/invite/xvzbAXk) server to communicate. Please also go through [Contributing.md](https://github.com/shikha-16/Women-in-Technology/blob/master/Contributing.md) and follow ALL instructions when making a PR, otherwise, it will be rejected.

For an overview of the project, see [here](https://github.com/shikha-16/Women-in-Technology/projects/1)

**Comment by wannabehacker007** [comment]
I can offer my help here!

**Comment by lucid-dreem** [comment]
I can help out as well!

**Comment by PeppermintNDaisies** [comment]
I can help too! What do you guys need?

**Comment by shikha-16** [comment]
> I can help too! What do you guys need?

Hi! Please join the discord server so we can talk there! @PeppermintNDaisies

**Comment by tory-brown** [comment]
Can i be assigned to it

**Comment by shikha-16** [comment]
> Can i be assigned to it
Hi @tory-brown sure.
I've assigned Inspirations and Scholarships carousels to you.

**Comment by bharati-21** [comment]
Hey @shikha-16, I can work on this as well. I can make carousels for Homepage, World of CS, and Organizations.
Thank you.

**Comment by wannabehacker007** [comment]
Hey there! I'd like to help out in designing the wireframes for the site on Figma. I would need editing permission to do that however!

**Comment by shikha-16** [comment]
> Hey there! I'd like to help out in designing the wireframes for the site on Figma. I would need editing permission to do that however!

the wireframes have already been made fully..... they are now not open to editing. If you want to help out, you can help actually design one of those pages above! @wannabehacker007

**Comment by wannabehacker007** [comment]
That was where I was getting at, actually. I can design one of the webpages for you. That's why I needed the editing permission for. I can duplicate the Figma file as well. Which page do you think is the most pressing right now?

**Comment by shikha-16** [comment]
> That was where I was getting at, actually. I can design one of the webpages for you. That's why I needed the editing permission for. I can duplicate the Figma file as well. Which page do you think is the most pressing right now?

oh, i see! sure we'll give you permission. choose any page you like.
