### ISSUE TITLE
Need a top navigation bar component for the website's home page

### ISSUE THREAD

**Issue by umang-sinha** [shikha-16/Women-in-Technology#31]
Contributors can take a look at the wireframe for the homepage [here](https://raw.githubusercontent.com/shikha-16/Women-in-Technology/website/website%20wireframes/Home%20page.png). 
Also, the top navigation bar needs to have dropdowns which appear when the user hovers over each of the items in the navigation bar. This is how it should look: [dropdowns](https://raw.githubusercontent.com/shikha-16/Women-in-Technology/website/website%20wireframes/Nav%20bar%20drop%20downs.png)

**Comment by ReddyAnanya9** [comment]
@umang-sinha I would like to work on this issue.

**Comment by umang-sinha** [comment]
@ReddyAnanya9 go ahead! Thanks for deciding to contribute.

**Comment by umang-sinha** [comment]
@ReddyAnanya9 an empty gatsby project has already been initialized in the 'website' branch. Please make sure you make your contributions there itself.

**Comment by ReddyAnanya9** [comment]
@umang-sinha  Thank you for informing.

**Comment by ReddyAnanya9** [comment]
@umang-sinha May I know if there is are any deadlines for the task and how can I contact you?

**Comment by umang-sinha** [comment]
@ReddyAnanya9 it would be great if you can finish this within the next 1-2 days. 
You can join our discord server to contact me. 
Here is the invite link: https://discord.gg/7PvCSu

**Comment by ReddyAnanya9** [comment]
@umang-sinha Okay. Thank you

**Comment by shikha-16** [comment]
@ReddyAnanya9 any updates on this?
Please join the discord server and introduce yourself
