### ISSUE TITLE
Need a carousel for the website's homepage

### ISSUE THREAD

**Issue by umang-sinha** [shikha-16/Women-in-Technology#32]
The homepage has a carousel that will be displayed right below the top navigation bar. Contributors may take a look at the wireframe for the website [here](https://raw.githubusercontent.com/shikha-16/Women-in-Technology/website/website%20wireframes/Home%20page.png)

**Comment by RidhikGovind** [comment]
Hey I could make a carousel. Could you assign this to me ?

**Comment by chinmaikaveti2001** [comment]
hi! sir can u please assign this issue to me..?
I want to work on this....

**Comment by shikha-16** [comment]
@RidhikGovind @chinmaikaveti2001 yes, you both can do this. you can decide if one of you wants it, you want to do it together, otherwise we will pick the one we like most. 
PLease go through Contributing.md and follow it for further communication. Thank you.

**Comment by RidhikGovind** [comment]
@shikha-16 So sorry for the removal of your assignment. I just think @chinmaikaveti2001 would be more suitable than me since I am a beginner. But thank you so much for providing me an opportunity for selecting me and Good luck !

**Comment by shikha-16** [comment]
@RidhikGovind no problem, please do contribute in other issues if you can!

**Comment by shikha-16** [comment]
@chinmaikaveti2001 ?? Please join discord grp

**Comment by shikha-16** [comment]
@RidhikGovind , @chinmaikaveti2001 hasn't been responding for a while now, any chance you're still willing to take this up?

**Comment by chinmaikaveti2001** [comment]
yes....@shiksha-16

**Comment by chinmaikaveti2001** [comment]
@shikha-16  ... I  want to work on this issue ....but  can u pls  help me to find the way  to work on it

**Comment by chinmaikaveti2001** [comment]
Because , i'm an absolute begineer to this open source contributions

**Comment by shikha-16** [comment]
Please join the discord server @chinmaikaveti2001 , we can talk there
https://discord.gg/xvzbAXk

**Comment by qwerty-rgb** [comment]
@shikha-16 i have worked on your repo before and one of my pr is in pending so if there is no problem i can take up the issue
And if so please assign me the task

**Comment by shikha-16** [comment]
> @shikha-16 i have worked on your repo before and one of my pr is in pending so if there is no problem i can take up the issue
> And if so please assign me the task

Yes sure

**Comment by qwerty-rgb** [comment]
I am unable to push the code can someone help me or send some documentation that how can i push the code. Its really very irritating when u have done the thing and cannot push the code to the repo

**Comment by shikha-16** [comment]
@umang-sinha please look into this

**Comment by RafaelDavisH** [comment]
@qwerty-rgb if you forked this Repo and then cloned it.  Then after create a branch through your terminal ‘git checkout -b website’.   After do ‘git pull origin website’ —

**Comment by shikha-16** [comment]
> I am unable to push the code can someone help me or send some documentation that how can i push the code. Its really very irritating when u have done the thing and cannot push the code to the repo

we have addressed it, please look properly

**Comment by qwerty-rgb** [comment]
i did both of that but then also git push is denying access.

**Comment by qwerty-rgb** [comment]
Error :(
![git](https://user-images.githubusercontent.com/58263441/95189501-909f4c80-07eb-11eb-91c2-b43651b4993c.PNG)

**Comment by qwerty-rgb** [comment]
#46

**Comment by umang-sinha** [comment]
@qwerty-rgb  you need to push changes to the repository that you forked from the original repository. You are unable to push code into it because you do not own the repository.

**Comment by qwerty-rgb** [comment]
thanks @umang-sinha #47

**Comment by qwerty-rgb** [comment]
#52
