### ISSUE TITLE
Need footer and top navigation components for all website pages.

### ISSUE THREAD

**Issue by umang-sinha** [shikha-16/Women-in-Technology#33]
Contributors may take a look at the wireframe for the website's homepage [here](https://github.com/shikha-16/Women-in-Technology/tree/master/documents/wireframes)
Please implement the footer and top navigation as mentioned in the wireframe. Also, add a button that takes the user back to the top of the page when clicked.

**Comment by qwerty-rgb** [comment]
I can do it please issue me the task

**Comment by shikha-16** [comment]
@qwerty-rgb sure.
I expect you to go through Cpntributing.md and follow all instructions there for further communication. Thank you.

**Comment by qwerty-rgb** [comment]
#35 pr request generated

**Comment by umang-sinha** [comment]
@qwerty-rgb There are a few changes that are required. I have put up a comment in the pull request thread. Please take a look.

**Comment by qwerty-rgb** [comment]
#37

**Comment by qwerty-rgb** [comment]
can u tell me what is wrong with pr so i can resolve as resolving would be much easy

**Comment by shikha-16** [comment]
@qwerty-rgb he has made a comment in the PR thread please see there.
Also, looks like you have made only the footer? can you also make the top navigation component?

**Comment by qwerty-rgb** [comment]
#48

**Comment by qwerty-rgb** [comment]
#52
