### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#4]
If anyone here is an expert on markdown styling, please take up this issue to make this repo look good. A good-looking repo attracts more people to its usefulness!

**Comment by shikha-16** [comment]
Would also appreciate if someone could make the links open in a new tab instead of the existing one.

**Comment by lucid-dreem** [comment]
I could help out with this!

**Comment by shikha-16** [comment]
That's great @lucid-dreem ! Do tell me what you plan to do! I'll assign this issue to you.

**Comment by shikha-16** [comment]
Great work! @lucid-dreem 
Thank you for contributing! 😄
