### ISSUE TITLE
Need footer and top navigation components for all website pages. 

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#53]
Contributors may take a look at the wireframe for the website's homepage [here](https://github.com/shikha-16/Women-in-Technology/tree/master/documents/wireframes) and the basic structure using gatsby and react.js [here](https://github.com/shikha-16/Women-in-Technology/tree/master/women-in-tech-website)
Please implement the footer and top navigation as mentioned in the wireframe. Also, add a button that takes the user back to the top of the page when clicked.

Whoever wants to contribute HAS to comment here AND join the [Discord](https://discord.com/invite/xvzbAXk) server to communicate. Please also go through [Contributing.md](https://github.com/shikha-16/Women-in-Technology/blob/master/Contributing.md) and follow ALL instructions when making a PR, otherwise, it will be rejected.

**Comment by PeppermintNDaisies** [comment]
Hello @shikha-16 do you still need this components?

**Comment by shikha-16** [comment]
> Hello @shikha-16 do you still need this components?

No, we do not
