### ISSUE TITLE
Carousel components

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#54]
The pages have a carousel that will be displayed right below the top navigation bar. Contributors may take a look at the wireframe for the website [here](https://raw.githubusercontent.com/shikha-16/Women-in-Technology/website/website%20wireframes/Home%20page.png) and the website basic skeleton [here](https://github.com/shikha-16/Women-in-Technology/tree/master/women-in-tech-website).

The carousel designs are [here](https://github.com/shikha-16/Women-in-Technology/tree/master/documents/design/carousels).

Whoever wants to contribute HAS to comment here AND join the [Discord](https://discord.com/invite/xvzbAXk) server to communicate. Please also go through [Contributing.md](https://github.com/shikha-16/Women-in-Technology/blob/master/Contributing.md) and follow ALL instructions when making a PR, otherwise, it will be rejected.

For an overview of the project, see [here](https://github.com/shikha-16/Women-in-Technology/projects/1)

**Comment by ddaniss** [comment]
I'd like to do it, is it ok if I use CSS?

**Comment by shikha-16** [comment]
> I'd like to do it, is it ok if I use CSS?

yes @ddaniss, you can use CSS. Using react will make it easier for you, but that's your call! 

We have some carousels designs ready so you could use those. PR will be made today for those. Meanwhile, here's the Figma link. [1](https://www.figma.com/file/B8WeO6ifqCdtRM6oXakqjW/WIT-Home-Page-2?node-id=0%3A1) and [2](https://www.figma.com/file/Vhyx8liScLBFjmSwRhqwon/WIT-Home-Page). The description will be up shortly. 

I'm assigning this issue to you! Looking forward to working with you.

**Comment by absenteerealitycheck** [comment]
@shikha-16  is this issue still open? Bc I would love to work on it

**Comment by shikha-16** [comment]
@absenteerealitycheck yes, it is open. The previous person has left. 
We need codes for the carousel components that have been designed: https://github.com/shikha-16/Women-in-Technology/tree/master/documents/design/carousels . These are 3, 2 more will be uploaded soon.
I'm assigning this issue to you! Looking forward to working with you.

**Comment by shikha-16** [comment]
@absenteerealitycheck i'll need you to respond and confirm?
