### ISSUE TITLE
Home Page for the website

### ISSUE THREAD

**Issue by umang-sinha** [shikha-16/Women-in-Technology#55]
Contributors interested in working on the home page for the website can take up this issue. You can have a look at the wireframes [here](https://www.figma.com/file/ctvCXdOEfS0U1xMEbLXQZY/Women-in-Technology-Wireframes?node-id=41%3A357).

The homepage needs to have the following components:
- top navigation bar (the top nav bar needs to have dropdowns. Please refer the wireframes and build accordingly)
- carousel (contributors working on this particular issue can skip the carousel as it has already been assigned to someone else)
- block of text
- 'the world of CS' section
- 'about the founder' section
- 'organizations promoting women in tech' section
- 'scholarships for women in tech' section
- 'inspirations for women in tech' section
- footer (the footer also needs to have a button that takes the user back to the top of the page when clicked)

Contributors are requested to strictly adhere to the format followed in the wireframes. Please go through [Contributing.md](https://github.com/shikha-16/Women-in-Technology/blob/master/Contributing.md) and the [basic skeleton](https://github.com/shikha-16/Women-in-Technology/tree/master/women-in-tech-website) before contributing.

Also join the [Discord](https://discord.com/invite/xvzbAXk) server so that communication can be done smoothly. 

For an overview of the project, see [here](https://github.com/shikha-16/Women-in-Technology/projects/1)

**Comment by greyGroot** [comment]
i would like to work on this one, @umang-sinha what do you think about adding material-ui to the project?

**Comment by umang-sinha** [comment]
Yes we are planning to go with material UI

**Comment by greyGroot** [comment]
please assign this issue to me.

**Comment by umang-sinha** [comment]
@greyGroot I am assigning this to you. You can go ahead and start working on it.

**Comment by shikha-16** [comment]
@greyGroot Meanwhile, here's the Figma link. [1](https://www.figma.com/file/B8WeO6ifqCdtRM6oXakqjW/WIT-Home-Page-2?node-id=0%3A1) and [2](https://www.figma.com/file/Vhyx8liScLBFjmSwRhqwon/WIT-Home-Page). The description will be up shortly.

**Comment by shikha-16** [comment]
@greyGroot , I'm emphasizing this again, you do NOT have to code for the carousels, somebody else is already working on that. Focus on the other parts and eave the carousels.

**Comment by shikha-16** [comment]
@greyGroot i need some response from you

**Comment by greyGroot** [comment]
@umang-sinha I'm working on it

**Comment by shikha-16** [comment]
> @shikha-16 I'm working on it

okay, you can refer to https://github.com/shikha-16/Women-in-Technology/issues/56 comments for the same. WE are looking for something exactly like that.

**Comment by greyGroot** [comment]
@shikha-16 as i see in pr #63 he was using bootstrap, but i thought want to add Material-UI. So what approach should i use?

**Comment by syauqy** [comment]
Hi @greyGroot @shikha-16 thanks for mention the issue. Personally, I think we need to decide the framework and I'm okay if we want to use material UI or any css framework. 

I was only focused on the skeleton of my page. But since the main components like navbar, carousel, and footer are missing, I took faster approach to work around that using bootstrap.

I'm happy to work on the update if we use another framework

**Comment by greyGroot** [comment]
@syauqy thank you for your contribution and happy to see that you ready to make update.

personally, i love to work with react material ui, but we can go with bootstrap, because Navigation, Footer and Carousel is ready.

**Comment by milenagd** [comment]
Personally, I prefer material ui as well.
I will wait for the decision to start working in the contribution page.

**Comment by umang-sinha** [comment]
Instead of getting into the hassle of updating #63 with material ui we should just proceed with bootstrap to make progress faster.

**Comment by greyGroot** [comment]
@umang-sinha there is small inconsistency in design of "Founder" block:

this option is from figma, home-page:
<img width="532" alt="Screenshot 2020-10-15 at 17 06 49" src="https://user-images.githubusercontent.com/41450089/96140756-f20c9d00-0f08-11eb-9d85-12f850c8edc6.png">

and this one from Community page:
<img width="522" alt="Screenshot 2020-10-15 at 17 07 00" src="https://user-images.githubusercontent.com/41450089/96140805-02247c80-0f09-11eb-8904-003f12bf9c06.png">

maybe we should align those two components?

**Comment by greyGroot** [comment]
@shikha-16 regarding carousel. @syauqy implemented main carousel, but we also have smaller one with cards, like here:

<img width="525" alt="Screenshot 2020-10-15 at 17 13 52" src="https://user-images.githubusercontent.com/41450089/96141609-d9e94d80-0f09-11eb-9a24-73ced68d39fb.png">

and here:

<img width="513" alt="Screenshot 2020-10-15 at 17 14 02" src="https://user-images.githubusercontent.com/41450089/96141635-deae0180-0f09-11eb-964b-6c79b36cf461.png">

Should i implement it, or somebody is working on it?

**Comment by shikha-16** [comment]
@greyGroot nobody is working on those. Can you please implement it? You can use the code made by him as reference!

**Comment by umang-sinha** [comment]
hey @greyGroot any updates on the issue?

**Comment by greyGroot** [comment]
@umang-sinha i was busy last few days, but now i'm working on it. it's in progress. 

Have you made a decision regarding "About Founder" block?

**Comment by umang-sinha** [comment]
> @umang-sinha i was busy last few days, but now i'm working on it. it's in progress.
> 
> Have you made a decision regarding "About Founder" block?

yes please go ahead with the one on the home page

**Comment by greyGroot** [comment]
@umang-sinha i'm working on carousel for cards, and i'm facing some troubles.

Here how it looks at the moment: https://youtu.be/z6_7aDI8xVE

On a design we have only one control on the right side. If user will click it, he should see next 4 cards, right?
How many slides there should be? Or how many cards in total?
If user will click on the right control, how he will be able to turn back to the first slide?

**Comment by greyGroot** [comment]
And as i see, there should be less cards on one slide on smaller screens, right?

**Comment by umang-sinha** [comment]
> @umang-sinha i'm working on carousel for cards, and i'm facing some troubles.
> 
> Here how it looks at the moment: https://youtu.be/z6_7aDI8xVE
> 
> On a design we have only one control on the right side. If user will click it, he should see next 4 cards, right?
> How many slides there should be? Or how many cards in total?
> If user will click on the right control, how he will be able to turn back to the first slide?

I guess that is an inconsistency that was missed while making the wireframes. To tackle this lets enable horizontal scrolling in those slides. When the users scrolls down they will move towards the rightmost slide and vice versa.
Regarding the total number of slides, I don't think I have a fixed number in mind. That depends on the amount of content we have to display. For now just create 6-7 slides to get the gist of how it will actually look when implemented.

**Comment by umang-sinha** [comment]
> And as i see, there should be less cards on one slide on smaller screens, right?

Yes. Try to make it responsive to smaller screens using media query or any other means

**Comment by greyGroot** [comment]
@umang-sinha ok, then i will add control on the left side of slider. will reduce amount of cards according to table size.

**Comment by shikha-16** [comment]
@greyGroot updates? when will you be done by?

**Comment by greyGroot** [comment]
@shikha-16 i will have time to work on this one only on the weekends

**Comment by shikha-16** [comment]
> @shikha-16 i will have time to work on this one only on the weekends
> 

Please set a deadline so that you are motivated to work, and we have something to work with as well.
