### ISSUE TITLE
Scholarships page for the website

### ISSUE THREAD

**Issue by umang-sinha** [shikha-16/Women-in-Technology#56]
Contributors interested in working on the scholarships page can take up this issue. You can have a look at the wireframes [here](https://www.figma.com/file/ctvCXdOEfS0U1xMEbLXQZY/Women-in-Technology-Wireframes?node-id=59%3A31).

The scholarships page needs to have the following components:
- top navigation bar (the top nav bar needs to have dropdowns. Please refer the wireframes and build accordingly)
- carousel (contributors working on this particular issue can skip the carousel as it has already been assigned to someone else)
- list of scholarships
- footer (the footer also needs to have a button that takes the user back to the top of the page when clicked)

Contributors are requested to strictly adhere to the format followed in the wireframes. Please go through [Contributing.md](https://github.com/shikha-16/Women-in-Technology/blob/master/Contributing.md) and the [basic skeleton](https://github.com/shikha-16/Women-in-Technology/tree/master/women-in-tech-website) before contributing.

Also join the [Discord](https://discord.com/invite/xvzbAXk) server so that communication can be done smoothly. 

For an overview of the project, see [here](https://github.com/shikha-16/Women-in-Technology/projects/1)

**Comment by syauqy** [comment]
Hi @umang-sinha what a great initiative! Can I on this?

**Comment by umang-sinha** [comment]
Hey @syauqy thanks for deciding to contribute. I am assigning this to you. You may go ahead and start working on it.

**Comment by shikha-16** [comment]
> Hi @umang-sinha what a great initiative! Can I work on this?

Hi @syauqy I'm assuming you'll be making the figma design(or any other software) and CSS/react code both yourself?

**Comment by syauqy** [comment]
Hi @shikha-16 since the project only has the wireframe. I think it's better if it push to the high fidelity first. I can help you with Figma for this page as long as we have decided the design guidelines to make sure it doesn't have different style compare to other pages. And also for the react/Gatsby I think I need to wait for the main project to setup first then I can working on this page. What do you think?

**Comment by umang-sinha** [comment]
Hey @syauqy We have some people working on the website designs. In this issue you are only expected to create a basic skeleton of the page. Further enhancements will be done only once the final designs for the other pages are ready. However you can take a look at the final design for the homepage to get a rough idea : https://www.figma.com/file/B8WeO6ifqCdtRM6oXakqjW/WIT-Home-Page-2?node-id=0%3A1

**Comment by umang-sinha** [comment]
Hey @syauqy We have some people working on the website designs. In this issue you are only expected to create a basic skeleton of the page. Further enhancements will be done only once the final designs for the other pages are ready. However you can take a look at the final design for the homepage to get a rough idea : https://www.figma.com/file/B8WeO6ifqCdtRM6oXakqjW/WIT-Home-Page-2?node-id=0%3A1

**Comment by syauqy** [comment]
Hi @shikha-16 and @umang-sinha please check this video of my progress on this page https://www.loom.com/share/f5a2a981d043428387c0fd68e31425a9
I want to make sure it's enough and I can open the PR for this issue.

Here are the screenshots of my work.
Responsive
![responsive](https://ik.imagekit.io/ps3xes4nrg/WIT_responsive_-1LJAlBXlrR.png)

Desktop header
![desktop1](https://ik.imagekit.io/ps3xes4nrg/localhost_8000_scholarship__1__Si_QaTUEY.png)

Desktop footer
![desktop2](https://ik.imagekit.io/ps3xes4nrg/localhost_8000_scholarship__2__hawe6jTQ_Cs.png)

**Comment by shikha-16** [comment]
Hi @syauqy WOW that looks great. thank you for this amazing work. 
So we already have the logo and favicon ready: https://github.com/shikha-16/Women-in-Technology/tree/master/documents/logo so that's something you can add.

We also have the carousel designs ready: https://github.com/shikha-16/Women-in-Technology/tree/master/documents/design/carousels if you want to use those (it's fine if you don't rn)

Everything else looks great to me! Add the logo and favicon, let @umang-sinha also comment, and then you're good to go!

**Comment by umang-sinha** [comment]
Hey @syauqy This looks perfect to me. This is exactly what we wanted. Great job! As @shikha-16 mentioned, please add the logo and favicons and then you can proceed to make a pull request.

**Comment by syauqy** [comment]
Logo and favicons added
![favicon added](https://ik.imagekit.io/ps3xes4nrg/WIT_favicon_Kct2KlOvrzoY.png)
Yes, for reusable components like carousel, navbar, and footer, I think we need to work on that separately

**Comment by syauqy** [comment]
please check my PR here #63 . Thanks @umang-sinha @shikha-16

**Comment by shikha-16** [comment]
@syauqy hi, please check out the comment on your PR

**Comment by shikha-16** [comment]
@syauqy maybe you would like to take up another page on the website? we really liked your work, and hope you can contribute more.

**Comment by syauqy** [comment]
Hi @shikha-16 thank you for the offer. Sure, but I think I cannot do it fast. Since I'm only able to work on it on the weekend. Let's see
