### ISSUE TITLE
Contribution page for the website

### ISSUE THREAD

**Issue by umang-sinha** [shikha-16/Women-in-Technology#57]
Contributors interested in working on the contributions page can take up this issue. You can have a look at the wireframes [here](https://www.figma.com/file/ctvCXdOEfS0U1xMEbLXQZY/Women-in-Technology-Wireframes?node-id=13%3A13).

The contributions page needs to have the following components:
- top navigation bar (the top nav bar needs to have dropdowns. Please refer the wireframes and build accordingly)
- a representational image with a button that takes the user to the github repo
- guidelines for contributors
- beginners section
- footer (the footer also needs to have a button that takes the user back to the top of the page when clicked)

Contributors are requested to strictly adhere to the format followed in the wireframes. Please go through [Contributing.md](https://github.com/shikha-16/Women-in-Technology/blob/master/Contributing.md) and the [basic skeleton](https://github.com/shikha-16/Women-in-Technology/tree/master/women-in-tech-website) before contributing.

Also join the [Discord](https://discord.com/invite/xvzbAXk) server so that communication can be done smoothly. 
For an overview of the project, see [here](https://github.com/shikha-16/Women-in-Technology/projects/1)

**Comment by milenagd** [comment]
Hey @shikha-16 can I take this one?

**Comment by shikha-16** [comment]
> Hey @shikha-16 can I take this one?

yes, sure!

**Comment by shikha-16** [comment]
> Hey @shikha-16 can I take this one?
I'll need some response from you @milenagd 

You can refer to https://github.com/shikha-16/Women-in-Technology/issues/56 comments for the same. We are looking for something exactly like that.

**Comment by milenagd** [comment]
Yes, I will work on it :)
Ok, I will check the #56
Thank you @shikha-16

**Comment by umang-sinha** [comment]
hey @milenagd any updates on this one?

**Comment by milenagd** [comment]
Sorry, I did not have time these days. I am working on it now
