### ISSUE TITLE
Resources page for the website

### ISSUE THREAD

**Issue by umang-sinha** [shikha-16/Women-in-Technology#58]
Contributors interested in working on the resources page can take up this issue. You can have a look at the wireframes [here](https://www.figma.com/file/ctvCXdOEfS0U1xMEbLXQZY/Women-in-Technology-Wireframes?node-id=42%3A138).

The resources page needs to have the following components:
- top navigation bar (the top nav bar needs to have dropdowns. Please refer the wireframes and build accordingly)
- block of text
- carousel (contributors working on this particular issue can skip the carousel as it has already been assigned to someone else)
- hyperlinks to scholarships page, organizations page and the world of CS page
- 'articles and blogs' section
- 'GitHub repositories to star' section
- Repository of the month section
- carousel (contributors working on this particular issue can skip the carousel as it has already been assigned to someone else)
- footer (the footer also needs to have a button that takes the user back to the top of the page when clicked)

Contributors are requested to strictly adhere to the format followed in the wireframes. Please go through [Contributing.md](https://github.com/shikha-16/Women-in-Technology/blob/master/Contributing.md) and the [basic skeleton](https://github.com/shikha-16/Women-in-Technology/tree/master/women-in-tech-website) before contributing.

Also join the [Discord](https://discord.com/invite/xvzbAXk) server so that communication can be done smoothly. 

For an overview of the project, see [here](https://github.com/shikha-16/Women-in-Technology/projects/1)

**Comment by tory-brown** [comment]
hello @shikha-16 its brownie from the discord channel, I'm working on community page and organizations promoting WIT. I cant find the issues here to officially comment  and be assigned

**Comment by ayush015** [comment]
@umang-sinha Can I have a look ?

**Comment by shikha-16** [comment]
@ayush015 yes, so we're looking for something like #56 comments, please check that out, and confirm.

**Comment by umang-sinha** [comment]
@ayush015 please let us know if you are working on this

**Comment by ayush015** [comment]
@umang-sinha Yeah I'm on it.

**Comment by shikha-16** [comment]
> @umang-sinha Yeah I'm on it.
> 

Updates? Please set a deadline for yourself too.

**Comment by ayush015** [comment]
hey @shikha-16 I have been very busy lately . I have started the project but due my work i'm not able to complete it . So if you want to assign it someone else its completely fine .
Thanks

**Comment by Hina-softwareEngineer** [comment]
Hi, I am Hina, I want to work on this issue. Can you please assign this to me?

**Comment by umang-sinha** [comment]
yes @Hina-softwareEngineer please go ahead. I am assigning this to you

**Comment by Hina-softwareEngineer** [comment]
Hi all, I have done this. Please take a look : [#80](https://github.com/shikha-16/Women-in-Technology/pull/80)

**Comment by umang-sinha** [comment]
thanks for contributing @Hina-softwareEngineer
