### ISSUE TITLE
Discord Channel Bot

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#6]
Any number of bots can be suggested for community management. To prevent haters, use of bad words, etc. to make sure the commuity is safe!

**Comment by arvind-iyer-2001** [comment]
I recommend using MEE6 bot as a moderator for the Discord Server - Women in Technology.
Visit the link to know more [https://mee6.xyz/](url)

**Comment by shikha-16** [comment]
> I recommend using MEE6 bot as a moderator for the Discord Server - Women in Technology.
> Visit the link to know more [https://mee6.xyz/](url)

Thank you!
