### ISSUE TITLE
Inspirations page for the website

### ISSUE THREAD

**Issue by umang-sinha** [shikha-16/Women-in-Technology#67]
Contributors interested in working on the inspirations page can take up this issue. You can have a look at the wireframes [here](https://www.figma.com/file/ctvCXdOEfS0U1xMEbLXQZY/Women-in-Technology-Wireframes?node-id=42%3A138).

The inspirations page needs to have the following components:
- top navigation bar (the top nav bar needs to have dropdowns. Please refer the wireframes and build accordingly)
- carousel
- list of inspiring women in tech
- footer (the footer also needs to have a button that takes the user back to the top of the page when clicked)

Some of these components (top navbar, footer etc.) will stay the same irrespective of the page that they exist on. You may refer to #56 and reuse the same code.

Contributors are requested to strictly adhere to the format followed in the wireframes. Please go through [Contributing.md](https://github.com/shikha-16/Women-in-Technology/blob/master/Contributing.md) and the [basic skeleton](https://github.com/shikha-16/Women-in-Technology/tree/master/women-in-tech-website) before contributing.

Also join the [Discord](https://discord.com/invite/xvzbAXk) server so that communication can be done smoothly. 

For an overview of the project, see [here](https://github.com/shikha-16/Women-in-Technology/projects/1)

**Comment by tory-brown** [comment]
I've seen the wire frames, thought someone was already working on it, if its still open i can take it

**Comment by umang-sinha** [comment]
@tory-brown I am assigning this to you. Please go ahead.

**Comment by tory-brown** [comment]
On it.

**Comment by prishison** [comment]
Hello, I would like to take up the issue
