### ISSUE TITLE
Organizations page for the website

### ISSUE THREAD

**Issue by umang-sinha** [shikha-16/Women-in-Technology#68]
Contributors interested in working on the organizations page can take up this issue. You can have a look at the wireframes [here](https://www.figma.com/file/ctvCXdOEfS0U1xMEbLXQZY/Women-in-Technology-Wireframes?node-id=42%3A138).

The organizations page needs to have the following components:
- top navigation bar (the top nav bar needs to have dropdowns. Please refer the wireframes and build accordingly)
- carousel
- list of organizations supporting women in tech
- footer (the footer also needs to have a button that takes the user back to the top of the page when clicked)

Some of these components (top navbar, footer etc.) will stay the same irrespective of the page that they exist on. You may refer to #56 and reuse the same code.

Contributors are requested to strictly adhere to the format followed in the wireframes. Please go through [Contributing.md](https://github.com/shikha-16/Women-in-Technology/blob/master/Contributing.md) and the [basic skeleton](https://github.com/shikha-16/Women-in-Technology/tree/master/women-in-tech-website) before contributing.

Also join the [Discord](https://discord.com/invite/xvzbAXk) server so that communication can be done smoothly. 

For an overview of the project, see [here](https://github.com/shikha-16/Women-in-Technology/projects/1)

**Comment by Hina-softwareEngineer** [comment]
Hi, I am Hina. I want to work on this issue. Can you please assign it to me?

**Comment by umang-sinha** [comment]
Yes @Hina-softwareEngineer please go ahead. I am assigning this to you.

**Comment by Hina-softwareEngineer** [comment]
Hi, I have done with the organization page. Can you please take a look? Here is my PR [#73 ](https://github.com/shikha-16/Women-in-Technology/pull/73)

**Comment by umang-sinha** [comment]
Hey @Hina-softwareEngineer Everything looks fine to me. Please post a screenshot or a short video displaying how the page looks and we will be good to go.

**Comment by Hina-softwareEngineer** [comment]
> Hey @Hina-softwareEngineer Everything looks fine to me. Please post a screenshot or a short video displaying how the page looks and we will be good to go.

That's great. Sure. If there is any kind of problem you see. Tell me, I will resolve it. 😄😄

![wominInTech](https://user-images.githubusercontent.com/56507951/97113485-8a2a3380-170c-11eb-8a98-159e08885210.png)

**Comment by umang-sinha** [comment]
@Hina-softwareEngineer  The 'scroll to top' button is missing in the footer. Please refer to https://github.com/shikha-16/Women-in-Technology/issues/56#issuecomment-707687777 and implement the same.

**Comment by Hina-softwareEngineer** [comment]
Hey, The 'scroll to top' button is not missing. Actually My screenshot extension is unable to capture it. Here is the image capture by laptop screenshot software.
![z1](https://user-images.githubusercontent.com/56507951/97182878-e51c6300-17be-11eb-8a0b-7c08c79f9f02.png)
and here is mobile responsive. the scroll to top is not showing in the below image due to screenshot extension
![mobile res](https://user-images.githubusercontent.com/56507951/97183086-257be100-17bf-11eb-9d99-7488cd1a7089.png)

**Comment by umang-sinha** [comment]
Great job @Hina-softwareEngineer ! Thanks for contributing.
