### ISSUE TITLE
Website for this repo

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#7]
If anyone is willing to make a website out of this repository, that would be great!

**Comment by umang-sinha** [comment]
I would like to take this up

**Comment by shikha-16** [comment]
@umang-sinha do communicate your ideas here!

**Comment by SudeepaNoble** [comment]
For the scholarship section, connect to the previous scholars and ask them to give tips. It would be helpful for the viewers/aspirants. 

I think my article for WTM Scholarship helps. 
It's [here](https://medium.com/@sudeepa.kolli/google-wtm-apac-scholarship-2020-9dabe5ddf052
[wtmdoc.docx](https://github.com/shikha-16/Women-in-Technology/files/5182629/wtmdoc.docx)
).

**Comment by shikha-16** [comment]
> For the scholarship section, connect to the previous scholars and ask them to give tips. It would be helpful for the viewers/aspirants.
> 
> I think my article for WTM Scholarship helps.
> (https://medium.com/@sudeepa.kolli/google-wtm-apac-scholarship-2020-9dabe5ddf052).
> 
> [wtmdoc.docx](https://github.com/shikha-16/Women-in-Technology/files/5182633/wtmdoc.docx)

Hi @SudeepaNoble 
While I appreciate your suggestion, going forward please post in the issues section which asks for ideas. We can address it there.
This thread is for the website discussion only.
