### ISSUE TITLE
World of CS page for the website

### ISSUE THREAD

**Issue by umang-sinha** [shikha-16/Women-in-Technology#70]
Contributors interested in working on the World of CS page can take up this issue. You can have a look at the wireframes [here](https://www.figma.com/file/ctvCXdOEfS0U1xMEbLXQZY/Women-in-Technology-Wireframes?node-id=42%3A138).

The World of CS page needs to have the following components:
- top navigation bar (the top nav bar needs to have dropdowns. Please refer the wireframes and build accordingly)
- representational images with buttons (refer wireframes)
- footer (the footer also needs to have a button that takes the user back to the top of the page when clicked)

Some of these components (top navbar, footer etc.) will stay the same irrespective of the page that they exist on. You may refer to #56 and reuse the same code.

Contributors are requested to strictly adhere to the format followed in the wireframes. Please go through [Contributing.md](https://github.com/shikha-16/Women-in-Technology/blob/master/Contributing.md) and the [basic skeleton](https://github.com/shikha-16/Women-in-Technology/tree/master/women-in-tech-website) before contributing.

Also join the [Discord](https://discord.com/invite/xvzbAXk) server so that communication can be done smoothly. 

For an overview of the project, see [here](https://github.com/shikha-16/Women-in-Technology/projects/1)

**Comment by qwerty-rgb** [comment]
can i take up this issue

**Comment by shikha-16** [comment]
> can i take up this issue

@qwerty-rgb you can, but please makes ure you're following our style guidelines and make it accessible and clean like #56 . Go through all the guidelines first.

**Comment by shikha-16** [comment]
@qwerty-rgb are you working on this???

**Comment by qwerty-rgb** [comment]
i am working i will make the pr by tomorrow because my paper are ongoing.
hope u understand

**Comment by shikha-16** [comment]
> i am working i will make the pr by tomorrow because my paper are ongoing.
> hope u understand

okay, please finish it as soon as possible

**Comment by umang-sinha** [comment]
@qwerty-rgb any updates?

**Comment by shikha-16** [comment]
@qwerty-rgb ????

**Comment by webdevknow99** [comment]
do you any idea about the "References
Books" page

**Comment by shikha-16** [comment]
> do you any idea about the "References
> Books" page 
> 

Do you mean Resources?

**Comment by webdevknow99** [comment]
No, about page

**Comment by webdevknow99** [comment]
index page is empty 
so any idea about structure? 
and give me the symbol of women-in-Techonolgy

**Comment by shikha-16** [comment]
> index page is empty
> so any idea about structure?
> and give me the symbol of women-in-Techonolgy

@webdevknow99 we don't really understand what you're saying... maybe join the discord group and talk to us there, it will be easier to communicate.
