### ISSUE TITLE
Previous Scholars tips helps Aspirants. 

### ISSUE THREAD

**Issue by SudeepaNoble** [shikha-16/Women-in-Technology#8]
For the scholarship section, connect to the previous scholars and ask them to give tips. It would be helpful for the viewers/aspirants. 

I think my article for *WTM Scholarship* helps. 
(https://medium.com/@sudeepa.kolli/google-wtm-apac-scholarship-2020-9dabe5ddf052).

[wtmdoc.docx](https://github.com/shikha-16/Women-in-Technology/files/5182633/wtmdoc.docx)

**Comment by shikha-16** [comment]
@SudeepaNoble That's a great idea. Would you like to take up this issue?
You could create a separate page for the scholar's medium articles and link it to the original README.md

**Comment by SudeepaNoble** [comment]
> @SudeepaNoble That's a great idea. Would you like to take up this issue?
> You could create a separate page for the scholar's medium articles and link it to the original README.md

Sure, I'll do that!
