### ISSUE TITLE
Add Myntra HackerRamp: WeForShe

### ISSUE THREAD

**Issue by itssingh** [shikha-16/Women-in-Technology#88]
Myntra has launched HackerRamp: WeForShe this year. This is an opportunity for all women coders from engineering colleges across the country to create and innovate through technology.

**Comment by shikha-16** [comment]
> Myntra has launched HackerRamp: WeForShe this year. This is an opportunity for all women coders from engineering colleges across the country to create and innovate through technology.

Hi! Would you like to add info for this on the README? Unfortunately, this year's registrations have closed but you can add it so that people can look out for it next year!
