### ISSUE TITLE
Events/Programs section in website

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#91]
![image](https://user-images.githubusercontent.com/68149849/121062783-25c36c80-c7e3-11eb-9bdc-11fbbb0b0a8a.png)

I want a page in the website in the 'Resources' section for these as well. Please go through the code and comment here if you are willing to contribute. Thanks! :)
Website - https://women-in-technology-wit.web.app/

**Comment by rishkwal** [comment]
Hey, I can work on this

**Comment by shikha-16** [comment]
> Hey, I can work on this

Go ahead, I am assigning you! Join the discord server to communicate.
