### ISSUE TITLE
Make carousel clickable

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#92]
![image](https://user-images.githubusercontent.com/68149849/121063454-f06b4e80-c7e3-11eb-8333-09aefe47f130.png)

This 'See More' button should redirect to a link - https://github.com/ossu/computer-science

**Comment by pratishtha-abrol** [comment]
I think I can do this, can I take this up?

**Comment by shikha-16** [comment]
> I think I can do this, can I take this up?

Yeah sure! @pratishtha-abrol I'm assigning you. If possible, please make a clearer images as well for the carousels.

**Comment by pratishtha-abrol** [comment]
Okay sure! I'll try improving the quality, also should I make them all the same size?

**Comment by shikha-16** [comment]
> Okay sure! I'll try improving the quality, also should I make them all the same size?

Yeah! The carousels are available separately in the documents folder. You can take from there.
