### ISSUE TITLE
Add extra slide with logo in homepage carousel

### ISSUE THREAD

**Issue by shikha-16** [shikha-16/Women-in-Technology#94]
![image](https://user-images.githubusercontent.com/68149849/121065068-f82bf280-c7e5-11eb-81bc-7fa3b583d3cf.png)
Add this slide to homepage carousel

**Comment by pratishtha-abrol** [comment]
Hi, can I take this up?

**Comment by shikha-16** [comment]
> Hi, can I take this up?

Yes sure!! I'm assigning you. Join the discord server to communicate.
